name: "Real World Conduit Backend CI"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Builds the test containers
      - run: docker compose -f ./docker-compose.test.yml build
      - name: Runs the tests
      - run: docker compose -f ./docker-compose.test.yml up
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint codebase using Rubocop
      - run: docker build -t lint-backend -f ./Dockerfile.lint .
      - run: docker run lint-backend
      
